const DB_NAME='blood-vault-db',DB_VERSION=1,REPORT_STORE='reports',PDF_STORE='pdfs';
const i18n={it:{privateArchive:'Archivio privato locale',yourHealthData:'I tuoi dati, sul tuo dispositivo',heroTitle:'Conserva i referti e struttura i valori degli esami del sangue.',heroBody:'I dati e i PDF restano nel browser del dispositivo. Puoi esportare tutto in JSON per backup o migrazione.',newReport:'Nuovo referto',reports:'Referti',measurements:'Valori',loincCatalog:'Catalogo LOINC',exportJson:'Esporta JSON',importJson:'Importa JSON',emptyTitle:'Nessun referto salvato',emptyBody:'Aggiungi il primo esame e, se vuoi, allega il PDF originale.',searchTest:'Cerca esame',loincNote:"LOINC identifica l'osservazione; l'unità effettiva resta quella riportata dal laboratorio.",report:'Referto',date:'Data',laboratory:'Laboratorio',notes:'Note',addValue:'Aggiungi valore',deleteReport:'Elimina referto',save:'Salva',test:'Esame',value:'Valore',unit:'Unità',range:'Intervallo',remove:'Rimuovi',medicalDisclaimer:'Archivio personale: non fornisce diagnosi né interpretazioni mediche.',openPdf:'Apri PDF',edit:'Modifica',pdfAttached:'PDF allegato',noPdf:'Nessun PDF allegato',confirmDelete:'Eliminare definitivamente questo referto e il relativo PDF?',importDone:'Importazione completata',invalidJson:'File JSON non valido',catalogEmpty:'Nessun esame trovato'},en:{privateArchive:'Private local archive',yourHealthData:'Your data, on your device',heroTitle:'Keep reports and structure your blood-test results.',heroBody:'Data and PDFs stay in this device browser. Export everything as JSON for backup or migration.',newReport:'New report',reports:'Reports',measurements:'Values',loincCatalog:'LOINC catalog',exportJson:'Export JSON',importJson:'Import JSON',emptyTitle:'No reports saved',emptyBody:'Add your first blood test and optionally attach the original PDF.',searchTest:'Search test',loincNote:'LOINC identifies the observation; the actual unit remains the one reported by the laboratory.',report:'Report',date:'Date',laboratory:'Laboratory',notes:'Notes',addValue:'Add value',deleteReport:'Delete report',save:'Save',test:'Test',value:'Value',unit:'Unit',range:'Reference range',remove:'Remove',medicalDisclaimer:'Personal archive: it does not provide diagnoses or medical interpretation.',openPdf:'Open PDF',edit:'Edit',pdfAttached:'PDF attached',noPdf:'No PDF attached',confirmDelete:'Permanently delete this report and its PDF?',importDone:'Import complete',invalidJson:'Invalid JSON file',catalogEmpty:'No tests found'}};
let lang=localStorage.getItem('blood-vault-lang')||'it',loinc=[],currentPdfBlob=null,currentPdfName='';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],t=k=>i18n[lang]?.[k]||i18n.en[k]||k,uuid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(REPORT_STORE))db.createObjectStore(REPORT_STORE,{keyPath:'id'});if(!db.objectStoreNames.contains(PDF_STORE))db.createObjectStore(PDF_STORE,{keyPath:'reportId'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function dbReq(store,mode,action){const db=await openDb();return new Promise((resolve,reject)=>{const tr=db.transaction(store,mode),req=action(tr.objectStore(store));req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
const getAllReports=()=>dbReq(REPORT_STORE,'readonly',s=>s.getAll()),getReport=id=>dbReq(REPORT_STORE,'readonly',s=>s.get(id)),putReport=r=>dbReq(REPORT_STORE,'readwrite',s=>s.put(r)),delReport=id=>dbReq(REPORT_STORE,'readwrite',s=>s.delete(id)),getPdf=id=>dbReq(PDF_STORE,'readonly',s=>s.get(id)),putPdf=(id,blob,name)=>dbReq(PDF_STORE,'readwrite',s=>s.put({reportId:id,blob,name,type:'application/pdf'})),delPdf=id=>dbReq(PDF_STORE,'readwrite',s=>s.delete(id));
function localName(x){return x.names?.[lang]||x.names?.en||x.loincName}function applyLanguage(){document.documentElement.lang=lang;$('#languageSelect').value=lang;$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));localStorage.setItem('blood-vault-lang',lang);fillDatalist();renderAll();renderCatalog();}
function fillDatalist(){$('#loincOptions').innerHTML=loinc.map(x=>`<option value="${x.code} — ${esc(localName(x))}"></option>`).join('')}
function findLoinc(input){const code=input.split(' — ')[0].trim().toLowerCase();return loinc.find(x=>x.code.toLowerCase()===code||localName(x).toLowerCase()===input.trim().toLowerCase())}
function addMeasurementRow(data={}){const node=$('#measurementTemplate').content.firstElementChild.cloneNode(true),search=node.querySelector('.test-search');search.value=data.loincCode?`${data.loincCode} — ${data.name||''}`:(data.name||'');node.dataset.loincCode=data.loincCode||'';node.querySelector('.test-value').value=data.value??'';node.querySelector('.test-unit').value=data.unit||'';node.querySelector('.test-range').value=data.referenceRange||'';search.addEventListener('change',()=>{const f=findLoinc(search.value);if(f){node.dataset.loincCode=f.code;search.value=`${f.code} — ${localName(f)}`;if(!node.querySelector('.test-unit').value)node.querySelector('.test-unit').value=f.commonUnits?.[0]||'';}});node.querySelector('.remove-measurement').onclick=()=>node.remove();$('#measurementEditor').appendChild(node)}
function readMeasurements(){return $$('#measurementEditor .measurement-row').map(row=>{const raw=row.querySelector('.test-search').value,f=findLoinc(raw);return{id:uuid(),loincCode:f?.code||row.dataset.loincCode||raw.split(' — ')[0].trim(),name:f?localName(f):raw.replace(/^.*? — /,''),value:row.querySelector('.test-value').value.trim(),unit:row.querySelector('.test-unit').value.trim(),referenceRange:row.querySelector('.test-range').value.trim()}})}
async function renderAll(){const reports=(await getAllReports()).sort((a,b)=>b.date.localeCompare(a.date));$('#reportCount').textContent=reports.length;$('#measurementCount').textContent=reports.reduce((n,r)=>n+(r.measurements?.length||0),0);$('#emptyState').classList.toggle('hidden',reports.length>0);$('#reportsList').innerHTML='';for(const r of reports){const pdf=await getPdf(r.id),el=document.createElement('article');el.className='glass report-card';el.innerHTML=`<div class="report-top"><div><h3>${esc(new Intl.DateTimeFormat(lang==='it'?'it-IT':'en-GB',{dateStyle:'long'}).format(new Date(`${r.date}T12:00:00`)))}</h3><div class="report-meta">${esc(r.laboratory||'')}</div></div><span class="pill">${r.measurements?.length||0} ${t('measurements').toLowerCase()}</span></div>${r.notes?`<p class="catalog-desc">${esc(r.notes)}</p>`:''}<div class="measurement-list">${(r.measurements||[]).map(m=>`<div class="measurement-item"><div><span class="measurement-name">${esc(m.name||m.loincCode)}</span><span class="measurement-code">LOINC ${esc(m.loincCode||'—')} · ${esc(m.referenceRange||'')}</span></div><div class="measurement-value">${esc(m.value)} ${esc(m.unit||'')}</div></div>`).join('')}</div><div class="report-actions"><button class="text-btn edit-report">${t('edit')}</button>${pdf?`<button class="text-btn open-pdf">${t('openPdf')}</button>`:''}</div>`;el.querySelector('.edit-report').onclick=()=>openReport(r.id);if(pdf)el.querySelector('.open-pdf').onclick=()=>{const url=URL.createObjectURL(pdf.blob);window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000)};$('#reportsList').appendChild(el)}}
function renderCatalog(){const q=($('#catalogSearch')?.value||'').trim().toLowerCase(),items=loinc.filter(x=>!q||x.code.toLowerCase().includes(q)||localName(x).toLowerCase().includes(q)||x.description?.[lang]?.toLowerCase().includes(q));$('#catalogList').innerHTML=items.length?items.map(x=>`<article class="glass catalog-card"><div class="catalog-row"><div><h3>${esc(localName(x))}</h3><span class="pill">LOINC ${esc(x.code)}</span></div></div><p class="catalog-desc">${esc(x.description?.[lang]||x.description?.en||'')}</p><div class="catalog-units">${esc((x.commonUnits||[]).join(' · '))}</div></article>`).join(''):`<div class="glass empty-state">${t('catalogEmpty')}</div>`}
async function openReport(id=''){currentPdfBlob=null;currentPdfName='';$('#reportForm').reset();$('#measurementEditor').innerHTML='';$('#reportId').value=id;$('#reportDate').value=new Date().toISOString().slice(0,10);$('#deleteReportBtn').classList.toggle('hidden',!id);if(id){const r=await getReport(id),pdf=await getPdf(id);$('#reportDate').value=r.date;$('#laboratory').value=r.laboratory||'';$('#notes').value=r.notes||'';(r.measurements||[]).forEach(addMeasurementRow);if(pdf){currentPdfBlob=pdf.blob;currentPdfName=pdf.name}}else addMeasurementRow();$('#pdfStatus').textContent=currentPdfBlob?`${t('pdfAttached')}: ${currentPdfName}`:t('noPdf');$('#reportDialog').showModal()}
$('#reportForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#reportId').value||uuid(),record={id,date:$('#reportDate').value,laboratory:$('#laboratory').value.trim(),notes:$('#notes').value.trim(),measurements:readMeasurements(),updatedAt:new Date().toISOString()};await putReport(record);if(currentPdfBlob)await putPdf(id,currentPdfBlob,currentPdfName||'report.pdf');$('#reportDialog').close();await renderAll()});
$('#pdfInput').addEventListener('change',e=>{const f=e.target.files?.[0];if(f){currentPdfBlob=f;currentPdfName=f.name;$('#pdfStatus').textContent=`${t('pdfAttached')}: ${f.name}`}});
$('#deleteReportBtn').onclick=async()=>{const id=$('#reportId').value;if(id&&confirm(t('confirmDelete'))){await delReport(id);await delPdf(id);$('#reportDialog').close();renderAll()}};
$('#newReportBtn').onclick=()=>openReport();$('#addMeasurementBtn').onclick=()=>addMeasurementRow();$('#closeDialogBtn').onclick=()=>$('#reportDialog').close();$('#languageSelect').onchange=e=>{lang=e.target.value;applyLanguage()};$('#catalogSearch').addEventListener('input',renderCatalog);
$$('.segment').forEach(btn=>btn.onclick=()=>{$$('.segment').forEach(x=>x.classList.toggle('active',x===btn));$$('.view').forEach(v=>v.classList.remove('active'));$(`#${btn.dataset.view}View`).classList.add('active')});
async function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)})}function dataUrlToBlob(url){const [meta,b64]=url.split(','),mime=meta.match(/:(.*?);/)?.[1]||'application/pdf',bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));return new Blob([bytes],{type:mime})}
$('#exportBtn').onclick=async()=>{const reports=await getAllReports(),pdfs=[];for(const r of reports){const p=await getPdf(r.id);if(p)pdfs.push({reportId:r.id,name:p.name,dataUrl:await blobToDataUrl(p.blob)})}const payload={schema:'blood-vault',version:1,exportedAt:new Date().toISOString(),reports,pdfs};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download=`blood-vault-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#importInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.schema!=='blood-vault'||!Array.isArray(data.reports))throw new Error();for(const r of data.reports)await putReport(r);for(const p of data.pdfs||[])await putPdf(p.reportId,dataUrlToBlob(p.dataUrl),p.name);alert(t('importDone'));renderAll()}catch{alert(t('invalidJson'))}e.target.value=''};
async function init(){loinc=await fetch('./loinc-common.json').then(r=>r.json());fillDatalist();applyLanguage();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');}init();
