const BIO_DB='blood-vault-db',BIO_DB_VERSION=2,BIO_META='meta',BIO_ITERATIONS=310000;
const enc=new TextEncoder(),dec=new TextDecoder();
const S={it:{manage:'Biometria',enable:'Abilita Face ID / impronta',disable:'Disabilita biometria',unlock:'Sblocca con biometria',unsupported:'Questo dispositivo/browser non offre un autenticatore biometrico WebAuthn utilizzabile.',prfUnsupported:'La biometria WebAuthn funziona, ma questo dispositivo non espone PRF: per sicurezza lo sblocco senza PIN non viene abilitato.',enterPin:'Inserisci il PIN attuale per associare la biometria.',wrongPin:'PIN non corretto.',enabled:'Sblocco biometrico abilitato su questo dispositivo.',disabled:'Sblocco biometrico disabilitato.',failed:'Autenticazione biometrica non riuscita.',secureOnly:'La biometria richiede HTTPS.',confirmDisable:'Disabilitare lo sblocco biometrico su questo dispositivo?'},en:{manage:'Biometrics',enable:'Enable Face ID / fingerprint',disable:'Disable biometrics',unlock:'Unlock with biometrics',unsupported:'This device/browser does not provide a usable WebAuthn platform authenticator.',prfUnsupported:'WebAuthn biometrics work, but this device does not expose PRF. For security, PIN-less vault unlock will not be enabled.',enterPin:'Enter the current PIN to bind biometrics.',wrongPin:'Incorrect PIN.',enabled:'Biometric unlock enabled on this device.',disabled:'Biometric unlock disabled.',failed:'Biometric authentication failed.',secureOnly:'Biometrics require HTTPS.',confirmDisable:'Disable biometric unlock on this device?'}};
const lang=()=>document.documentElement.lang==='en'?'en':'it',msg=k=>S[lang()][k]||S.en[k]||k;
const toB64=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))),fromB64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const toB64url=bytes=>toB64(bytes).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const fromB64url=s=>fromB64(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4));
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(BIO_DB,BIO_DB_VERSION);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function getMeta(id){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(BIO_META,'readonly'),r=tx.objectStore(BIO_META).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function putMeta(x){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(BIO_META,'readwrite'),r=tx.objectStore(BIO_META).put(x);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function delMeta(id){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(BIO_META,'readwrite'),r=tx.objectStore(BIO_META).delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
async function derivePinKey(pin,salt){const material=await crypto.subtle.importKey('raw',enc.encode(pin),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:BIO_ITERATIONS,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt']);}
async function verifyPin(pin){const sec=await getMeta('security');if(!sec)return false;try{const k=await derivePinKey(pin,fromB64(sec.salt));await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64(sec.wrappedKey.iv),additionalData:enc.encode('blood-vault-key-v2')},k,fromB64(sec.wrappedKey.ciphertext));return true}catch{return false}}
async function prfKey(secret){return crypto.subtle.importKey('raw',new Uint8Array(secret).slice(0,32),'AES-GCM',false,['encrypt','decrypt']);}
async function sealPin(secret,pin){const key=await prfKey(secret),iv=crypto.getRandomValues(new Uint8Array(12)),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode('blood-vault-biometric-pin-v1')},key,enc.encode(pin));return{iv:toB64(iv),ciphertext:toB64(ct)}}
async function openPin(secret,box){const key=await prfKey(secret),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64(box.iv),additionalData:enc.encode('blood-vault-biometric-pin-v1')},key,fromB64(box.ciphertext));return dec.decode(plain)}
function random(n=32){return crypto.getRandomValues(new Uint8Array(n))}
async function platformAvailable(){if(!window.isSecureContext||!window.PublicKeyCredential||!navigator.credentials)return false;try{return await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable()}catch{return false}}
function sameBytes(a,b){a=new Uint8Array(a);b=new Uint8Array(b);if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a[i]^b[i];return x===0}
async function verifyAssertion(cred,meta,challenge){const response=cred.response;const client=JSON.parse(dec.decode(response.clientDataJSON));if(client.type!=='webauthn.get'||client.origin!==location.origin||!sameBytes(fromB64url(client.challenge),challenge))return false;const auth=new Uint8Array(response.authenticatorData);if(auth.length<37)return false;const expectedRp=await crypto.subtle.digest('SHA-256',enc.encode(location.hostname));if(!sameBytes(auth.slice(0,32),expectedRp))return false;const flags=auth[32];if((flags&0x01)===0||(flags&0x04)===0)return false;const clientHash=await crypto.subtle.digest('SHA-256',response.clientDataJSON),signed=new Uint8Array(auth.byteLength+clientHash.byteLength);signed.set(auth,0);signed.set(new Uint8Array(clientHash),auth.byteLength);let algorithm,importAlg;if(meta.alg===-7){algorithm={name:'ECDSA',hash:'SHA-256'};importAlg={name:'ECDSA',namedCurve:'P-256'}}else if(meta.alg===-257){algorithm={name:'RSASSA-PKCS1-v1_5'};importAlg={name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'}}else return false;const pub=await crypto.subtle.importKey('spki',fromB64(meta.publicKey),importAlg,false,['verify']);return crypto.subtle.verify(algorithm,pub,response.signature,signed)}
async function getPrfWithCredential(credentialId,prfSalt){const challenge=random(),id=fromB64url(credentialId),key=credentialId;const cred=await navigator.credentials.get({publicKey:{challenge,rpId:location.hostname,allowCredentials:[{type:'public-key',id}],userVerification:'required',timeout:60000,extensions:{prf:{evalByCredential:{[key]:{first:fromB64(prfSalt)}}}}}});return{cred,challenge,result:cred.getClientExtensionResults()?.prf?.results?.first}}
async function enroll(){if(!await platformAvailable()){alert(window.isSecureContext?msg('unsupported'):msg('secureOnly'));return}const pin=prompt(msg('enterPin'));if(!pin)return;if(!await verifyPin(pin)){alert(msg('wrongPin'));return}const challenge=random(),userId=random(32),salt=random(32);let cred;try{cred=await navigator.credentials.create({publicKey:{challenge,rp:{name:'Blood Vault',id:location.hostname},user:{id:userId,name:'local-vault',displayName:'Blood Vault local vault'},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],authenticatorSelection:{authenticatorAttachment:'platform',residentKey:'preferred',userVerification:'required'},attestation:'none',timeout:60000,extensions:{prf:{eval:{first:salt}}}}})}catch(e){console.warn(e);alert(msg('failed'));return}const publicKey=cred.response.getPublicKey?.(),alg=cred.response.getPublicKeyAlgorithm?.();if(!publicKey||![-7,-257].includes(alg)){alert(msg('unsupported'));return}const credentialId=toB64url(cred.rawId);let secret=cred.getClientExtensionResults()?.prf?.results?.first;try{if(!secret){const test=await getPrfWithCredential(credentialId,toB64(salt));secret=test.result}}catch(e){console.warn('PRF assertion test failed',e)}if(!secret){alert(msg('prfUnsupported'));return}const pinBox=await sealPin(secret,pin);await putMeta({id:'biometric',version:1,credentialId,prfSalt:toB64(salt),publicKey:toB64(publicKey),alg,pinBox,createdAt:new Date().toISOString(),rpId:location.hostname,origin:location.origin});await refresh();alert(msg('enabled'))}
async function biometricUnlock(){const meta=await getMeta('biometric');if(!meta)return;try{if(meta.rpId!==location.hostname||meta.origin!==location.origin)throw new Error('origin mismatch');const {cred,challenge,result}=await getPrfWithCredential(meta.credentialId,meta.prfSalt);if(!result||!await verifyAssertion(cred,meta,challenge))throw new Error('assertion verification failed');const pin=await openPin(result,meta.pinBox),input=document.querySelector('#pinInput'),btn=document.querySelector('#unlockBtn');input.value=pin;btn.click();setTimeout(()=>{input.value=''},0)}catch(e){console.warn('Biometric unlock',e);alert(msg('failed'))}}
async function toggle(){const meta=await getMeta('biometric');if(meta){if(confirm(msg('confirmDisable'))){await delMeta('biometric');await refresh();alert(msg('disabled'))}}else await enroll()}
async function refresh(){const meta=await getMeta('biometric'),unlock=document.querySelector('#biometricUnlockBtn'),manage=document.querySelector('#biometricManageBtn');if(unlock){unlock.classList.toggle('hidden',!meta);unlock.textContent=msg('unlock')}if(manage)manage.textContent=meta?msg('disable'):msg('enable')}
document.querySelector('#biometricUnlockBtn')?.addEventListener('click',biometricUnlock);
document.querySelector('#biometricManageBtn')?.addEventListener('click',toggle);
new MutationObserver(refresh).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
refresh();
