const DB_NAME='riferto-db',DB_VERSION=1,VAULT_STORE='vault',META_STORE='meta';
const ITERATIONS=310000,te=new TextEncoder(),td=new TextDecoder();
let lang=localStorage.getItem('riferto-lang')||'it',loinc=[],vaultKey=null,pendingPdfFiles=[],removedPdfIds=[],currentPdfAttachments=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],uuid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
const strings={it:{newReport:'Nuovo referto',reports:'Referti',values:'Valori',catalog:'Catalogo LOINC',export:'Esporta backup cifrato',import:'Importa backup',empty:'Nessun referto salvato',emptyBody:'Aggiungi il primo referto e, se vuoi, allega il PDF originale.',lock:'Blocca',update:'Aggiorna app',bio:'Face ID / impronta',create:'Crea archivio',unlock:'Sblocca archivio',first:'Crea un PIN di almeno 6 cifre per proteggere l’archivio locale.',again:'Inserisci il PIN per aprire l’archivio locale.',short:'Usa almeno 6 caratteri.',mismatch:'I PIN non coincidono.',wrong:'PIN errato.',openPdf:'Apri PDF',edit:'Modifica',confirmDelete:'Eliminare definitivamente questo referto e tutti i PDF allegati?',noPdf:'Nessun PDF allegato',pdf:'PDF allegato',backupPrompt:'Inserisci una password di almeno 6 caratteri per cifrare il backup.',backupImport:'Inserisci la password del backup.',badBackup:'Backup non valido o password errata.',importDone:'Importazione completata.',catalogEmpty:'Nessun esame trovato.'},en:{newReport:'New report',reports:'Reports',values:'Values',catalog:'LOINC catalog',export:'Export encrypted backup',import:'Import backup',empty:'No reports saved',emptyBody:'Add your first report and optionally attach the original PDF.',lock:'Lock',update:'Update app',bio:'Face ID / fingerprint',create:'Create archive',unlock:'Unlock archive',first:'Create a PIN of at least 6 digits to protect the local archive.',again:'Enter your PIN to open the local archive.',short:'Use at least 6 characters.',mismatch:'PINs do not match.',wrong:'Wrong PIN.',openPdf:'Open PDF',edit:'Edit',confirmDelete:'Permanently delete this report and all attached PDFs?',noPdf:'No PDF attached',pdf:'PDF attached',backupPrompt:'Enter a password of at least 6 characters to encrypt the backup.',backupImport:'Enter the backup password.',badBackup:'Invalid backup or wrong password.',importDone:'Import complete.',catalogEmpty:'No tests found.'}};
const t=k=>strings[lang]?.[k]||strings.it[k]||k;
function bytesToB64(input){const bytes=input instanceof Uint8Array?input:new Uint8Array(input);let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
function b64ToBytes(s){const binary=atob(s),out=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)out[i]=binary.charCodeAt(i);return out}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(VAULT_STORE))db.createObjectStore(VAULT_STORE,{keyPath:'id'});if(!db.objectStoreNames.contains(META_STORE))db.createObjectStore(META_STORE,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function req(store,mode,action){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode),r=action(tx.objectStore(store));r.onsuccess=()=>{db.close();resolve(r.result)};r.onerror=()=>{db.close();reject(r.error)}})}
const getMeta=id=>req(META_STORE,'readonly',s=>s.get(id)),putMeta=x=>req(META_STORE,'readwrite',s=>s.put(x)),getRaw=id=>req(VAULT_STORE,'readonly',s=>s.get(id)),getAllRaw=()=>req(VAULT_STORE,'readonly',s=>s.getAll()),putRaw=x=>req(VAULT_STORE,'readwrite',s=>s.put(x)),delRaw=id=>req(VAULT_STORE,'readwrite',s=>s.delete(id));
async function deriveKey(secret,salt,iterations=ITERATIONS){const material=await crypto.subtle.importKey('raw',te.encode(secret),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptBytes(key,bytes,aad=''){const iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:te.encode(aad)},key,bytes);return{iv:bytesToB64(iv),ciphertext:bytesToB64(cipher)}}
async function decryptBytes(key,box,aad=''){return crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(box.iv),additionalData:te.encode(aad)},key,b64ToBytes(box.ciphertext))}
const encryptJson=(key,obj,aad)=>encryptBytes(key,te.encode(JSON.stringify(obj)),aad);async function decryptJson(key,box,aad){return JSON.parse(td.decode(await decryptBytes(key,box,aad)))}
async function setupArchive(pin){const salt=crypto.getRandomValues(new Uint8Array(16)),pinKey=await deriveKey(pin,salt),raw=crypto.getRandomValues(new Uint8Array(32));vaultKey=await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']);await putMeta({id:'security',version:1,kdf:'PBKDF2-SHA256',iterations:ITERATIONS,salt:bytesToB64(salt),wrappedKey:await encryptBytes(pinKey,raw,'riferto-key-v1')})}
async function unlockArchive(pin){const meta=await getMeta('security');if(!meta)return false;try{const key=await deriveKey(pin,b64ToBytes(meta.salt),meta.iterations||ITERATIONS),raw=await decryptBytes(key,meta.wrappedKey,'riferto-key-v1');vaultKey=await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']);return true}catch{return false}}
async function putReport(r){await putRaw({id:`report:${r.id}`,kind:'report',box:await encryptJson(vaultKey,r,`riferto-report:${r.id}`)})}
async function getReport(id){const row=await getRaw(`report:${id}`);return row?decryptJson(vaultKey,row.box,`riferto-report:${id}`):null}
async function getAllReports(){const rows=(await getAllRaw()).filter(x=>x.kind==='report'),out=[];for(const row of rows)out.push(await decryptJson(vaultKey,row.box,`riferto-report:${row.id.slice(7)}`));return out}
const delReport=id=>delRaw(`report:${id}`);
async function putPdfAttachment(reportId,blob,name,attachmentId=uuid()){const storageId=`pdf:${reportId}:${attachmentId}`;await putRaw({id:storageId,kind:'pdf',reportId,attachmentId,nameBox:await encryptJson(vaultKey,{name:name||'referto.pdf'},`riferto-pdf-name:${reportId}:${attachmentId}`),box:await encryptBytes(vaultKey,await blob.arrayBuffer(),`riferto-pdf:${reportId}:${attachmentId}`)});return storageId}
async function decryptPdfRow(row,reportId){const legacy=row.id===`pdf:${reportId}`;const suffix=legacy?reportId:`${reportId}:${row.attachmentId||row.id.slice(`pdf:${reportId}:`.length)}`;const meta=await decryptJson(vaultKey,row.nameBox,`riferto-pdf-name:${suffix}`);return{storageId:row.id,attachmentId:legacy?'legacy':(row.attachmentId||row.id.slice(`pdf:${reportId}:`.length)),name:meta.name,blob:new Blob([await decryptBytes(vaultKey,row.box,`riferto-pdf:${suffix}`)],{type:'application/pdf'}),legacy}}
async function getPdfAttachments(reportId){const rows=(await getAllRaw()).filter(row=>row.kind==='pdf'&&(row.id===`pdf:${reportId}`||row.id.startsWith(`pdf:${reportId}:`))),out=[];for(const row of rows){try{out.push(await decryptPdfRow(row,reportId))}catch(error){console.warn('PDF non leggibile',row.id,error)}}return out}
async function delAllPdfs(reportId){const rows=(await getAllRaw()).filter(row=>row.kind==='pdf'&&(row.id===`pdf:${reportId}`||row.id.startsWith(`pdf:${reportId}:`)));for(const row of rows)await delRaw(row.id)}
function openPdfBlob(blob){const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)}
function renderPdfManager(){const host=$('#pdfStatus');if(!host)return;host.innerHTML='';const active=currentPdfAttachments.filter(p=>!removedPdfIds.includes(p.storageId));const pending=pendingPdfFiles;const allCount=active.length+pending.length;if(!allCount){host.innerHTML=`<span class="caption">${esc(t('noPdf'))}</span>`;return}const list=document.createElement('div');list.className='pdf-attachment-list';for(const item of active){const row=document.createElement('div');row.className='pdf-attachment-row';row.innerHTML=`<span class="pdf-attachment-name">${esc(item.name)}</span><div class="pdf-attachment-actions"><button type="button" class="text-btn pdf-open">Apri</button><button type="button" class="danger-link pdf-remove">Rimuovi</button></div>`;row.querySelector('.pdf-open').onclick=()=>openPdfBlob(item.blob);row.querySelector('.pdf-remove').onclick=()=>{removedPdfIds.push(item.storageId);renderPdfManager()};list.appendChild(row)}for(const item of pending){const row=document.createElement('div');row.className='pdf-attachment-row pending';row.innerHTML=`<span class="pdf-attachment-name">${esc(item.name)}</span><div class="pdf-attachment-actions"><span class="caption">Nuovo</span><button type="button" class="danger-link pdf-remove">Rimuovi</button></div>`;row.querySelector('.pdf-remove').onclick=()=>{pendingPdfFiles=pendingPdfFiles.filter(x=>x!==item);renderPdfManager()};list.appendChild(row)}host.appendChild(list)}
function localName(x){return x.names?.[lang]||x.names?.it||x.names?.en||x.loincName||x.code}
function fillDatalist(){$('#loincOptions').innerHTML=loinc.map(x=>`<option value="${esc(x.code)} — ${esc(localName(x))}"></option>`).join('')}
function findLoinc(input){const code=input.split(' — ')[0].trim().toLowerCase();return loinc.find(x=>x.code.toLowerCase()===code||localName(x).toLowerCase()===input.trim().toLowerCase())}
function unitSpec(unit){
  const raw=String(unit||'').trim(),u=raw.replace(/µ/g,'u').replace(/μ/g,'u').replace(/\s+/g,'').replace(/¹²/g,'^12').replace(/⁹/g,'^9').replace(/⁶/g,'^6').replace(/³/g,'^3');
  const map={
    'g/L':['massConc',1,'g/L'],'g/dL':['massConc',10,'g/dL'],'mg/L':['massConc',.001,'mg/L'],'mg/dL':['massConc',.01,'mg/dL'],'ug/L':['massConc',1e-6,'ug/L'],'ng/mL':['massConc',1e-6,'ng/mL'],
    '10^9/L':['cell',1e9,'10*9/L'],'10^12/L':['cell',1e12,'10*12/L'],'10^3/uL':['cell',1e9,'10*3/uL'],'10^6/uL':['cell',1e12,'10*6/uL'],
    '%':['percent',1,'%'],'pg':['pg',1,'pg'],'fL':['fL',1,'fL'],'mmol/L':['mmol',1,'mmol/L'],'umol/L':['umol',1,'umol/L'],'mEq/L':['meq',1,'meq/L'],'IU/L':['iu',1,'[IU]/L'],'mIU/L':['miu',1,'m[IU]/L'],'uIU/mL':['uiuml',1,'u[IU]/mL'],'ng/dL':['ngdl',1,'ng/dL'],'pg/mL':['pgml',1,'pg/mL'],'mg/g':['mgg',1,'mg/g']
  };
  return map[u]||[u||'unknown',1,raw||''];
}
function canonicalize(value,unit,targetUnit,range){
  const n=Number(String(value||'').replace(',','.')),source=unitSpec(unit),target=unitSpec(targetUnit||unit);
  const out={unitUcum:source[2],canonicalUnit:targetUnit||unit,canonicalValue:Number.isFinite(n)?n:null,canonicalRangeMin:null,canonicalRangeMax:null};
  if(Number.isFinite(n)&&source[0]===target[0])out.canonicalValue=n*source[1]/target[1];
  const m=String(range||'').match(/([\d.,]+)\s*[–—-]\s*([\d.,]+)/);
  if(m){const a=Number(m[1].replace(',','.')),b=Number(m[2].replace(',','.'));if(Number.isFinite(a)&&Number.isFinite(b)){out.canonicalRangeMin=source[0]===target[0]?a*source[1]/target[1]:a;out.canonicalRangeMax=source[0]===target[0]?b*source[1]/target[1]:b}}
  return out;
}
async function renderLockState(){const meta=await getMeta('security'),first=!meta;$('#pinConfirmField').classList.toggle('hidden',!first);$('#lockIntro').textContent=t(first?'first':'again');$('#unlockBtn').textContent=t(first?'create':'unlock')}
function applyLanguage(){document.documentElement.lang=lang;$('#languageSelect').value=lang;localStorage.setItem('riferto-lang',lang);$('#newReportBtn').textContent=t('newReport');$('#lockBtn').textContent=t('lock');$('#forceUpdateBtn').textContent=t('update');if(!$('#biometricManageBtn').textContent.includes('Disabilita'))$('#biometricManageBtn').textContent=t('bio');const seg=$$('.segment');if(seg[0])seg[0].textContent=t('reports');if(seg[1])seg[1].textContent=t('catalog');$('#exportBtn').textContent=t('export');$('.file-label span').textContent=t('import');$('#emptyState h3').textContent=t('empty');$('#emptyState p').textContent=t('emptyBody');fillDatalist();renderLockState();if(vaultKey){renderAll();renderCatalog()}}
function addMeasurementRow(data={}){const node=$('#measurementTemplate').content.firstElementChild.cloneNode(true),search=node.querySelector('.test-search');search.value=data.loincCode?`${data.loincCode} — ${data.name||''}`:(data.name||'');node.dataset.loincCode=data.loincCode||'';node.querySelector('.test-value').value=data.value??'';node.querySelector('.test-unit').value=data.unit||'';node.querySelector('.test-range').value=data.referenceRange||'';search.addEventListener('change',()=>{const f=findLoinc(search.value);if(f){node.dataset.loincCode=f.code;search.value=`${f.code} — ${localName(f)}`;if(!node.querySelector('.test-unit').value)node.querySelector('.test-unit').value=f.commonUnits?.[0]||''}});node.querySelector('.remove-measurement').onclick=()=>node.remove();$('#measurementEditor').appendChild(node)}
function readMeasurements(){return $$('#measurementEditor .measurement-row').map(row=>{const raw=row.querySelector('.test-search').value,f=findLoinc(raw),value=row.querySelector('.test-value').value.trim(),unit=row.querySelector('.test-unit').value.trim(),referenceRange=row.querySelector('.test-range').value.trim(),preferredUnit=f?.canonicalUnit||f?.commonUnits?.[0]||unit,standard=canonicalize(value,unit,preferredUnit,referenceRange);return{id:uuid(),loincCode:f?.code||row.dataset.loincCode||raw.split(' — ')[0].trim(),name:f?localName(f):raw.replace(/^.*? — /,''),value,unit,referenceRange,standardSystem:'UCUM',unitUcum:standard.unitUcum,canonicalValue:standard.canonicalValue,canonicalUnit:standard.canonicalUnit,canonicalRangeMin:standard.canonicalRangeMin,canonicalRangeMax:standard.canonicalRangeMax}})}
async function renderAll(){if(!vaultKey)return;const reports=(await getAllReports()).sort((a,b)=>b.date.localeCompare(a.date));$('#reportCount').textContent=reports.length;$('#measurementCount').textContent=reports.reduce((n,r)=>n+(r.measurements?.length||0),0);$('#emptyState').classList.toggle('hidden',reports.length>0);$('#reportsList').innerHTML='';for(const r of reports){const attachments=await getPdfAttachments(r.id),el=document.createElement('article');el.className='glass report-card';const date=new Intl.DateTimeFormat(lang==='it'?'it-IT':'en-GB',{dateStyle:'long'}).format(new Date(`${r.date}T12:00:00`));el.innerHTML=`<div class="report-top"><div><h3>${esc(date)}</h3><div class="report-meta">${esc(r.laboratory||'')}</div></div><span class="pill">${r.measurements?.length||0} ${t('values').toLowerCase()}</span></div>${r.notes?`<p class="catalog-desc">${esc(r.notes)}</p>`:''}<div class="measurement-list">${(r.measurements||[]).map(m=>`<div class="measurement-item" data-canonical-value="${esc(m.canonicalValue??'')}" data-canonical-unit="${esc(m.canonicalUnit||'')}" data-unit-ucum="${esc(m.unitUcum||'')}" data-canonical-min="${esc(m.canonicalRangeMin??'')}" data-canonical-max="${esc(m.canonicalRangeMax??'')}"><div><span class="measurement-name">${esc(m.name||m.loincCode)}</span><span class="measurement-code">LOINC ${esc(m.loincCode||'—')} · ${esc(m.referenceRange||'')}</span></div><div class="measurement-value">${esc(m.value)} ${esc(m.unit||'')}</div></div>`).join('')}</div><div class="report-actions"><button class="text-btn edit-report">${t('edit')}</button>${attachments.length?`<button class="text-btn open-pdf-main">${t('openPdf')}</button>`:''}</div>`;el.querySelector('.edit-report').onclick=()=>openReport(r.id);if(attachments.length){el.querySelector('.open-pdf-main').onclick=async event=>{event.stopPropagation();if(attachments.length===1){openPdfBlob(attachments[0].blob);return}await openReport(r.id);setTimeout(()=>$('#pdfStatus')?.scrollIntoView({behavior:'smooth',block:'center'}),100)}}$('#reportsList').appendChild(el)}}
function renderCatalog(){const q=$('#catalogSearch').value.trim().toLowerCase(),items=loinc.filter(x=>!q||x.code.toLowerCase().includes(q)||localName(x).toLowerCase().includes(q)||(x.description?.[lang]||x.description?.it||x.description?.en||'').toLowerCase().includes(q));$('#catalogList').innerHTML=items.length?items.map(x=>`<article class="glass catalog-card"><h3>${esc(localName(x))}</h3><span class="pill">LOINC ${esc(x.code)}</span><p class="catalog-desc">${esc(x.description?.[lang]||x.description?.it||x.description?.en||'')}</p><div class="catalog-units">${esc((x.commonUnits||[]).join(' · '))}</div></article>`).join(''):`<div class="glass empty-state">${t('catalogEmpty')}</div>`}
async function openReport(id=''){pendingPdfFiles=[];removedPdfIds=[];currentPdfAttachments=[];$('#reportForm').reset();$('#measurementEditor').innerHTML='';$('#reportId').value=id;$('#reportDate').value=new Date().toISOString().slice(0,10);$('#deleteReportBtn').classList.toggle('hidden',!id);$('#dialogTitle').textContent=id?t('edit'):t('newReport');if(id){const r=await getReport(id);currentPdfAttachments=await getPdfAttachments(id);$('#reportDate').value=r.date;$('#laboratory').value=r.laboratory||'';$('#notes').value=r.notes||'';(r.measurements||[]).forEach(addMeasurementRow)}else addMeasurementRow();renderPdfManager();$('#reportDialog').showModal()}
$('#reportForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#reportId').value||uuid(),record={id,date:$('#reportDate').value,laboratory:$('#laboratory').value.trim(),notes:$('#notes').value.trim(),measurements:readMeasurements(),updatedAt:new Date().toISOString()};await putReport(record);for(const storageId of removedPdfIds)await delRaw(storageId);for(const file of pendingPdfFiles)await putPdfAttachment(id,file,file.name);pendingPdfFiles=[];removedPdfIds=[];currentPdfAttachments=[];$('#reportDialog').close();await renderAll()});
$('#pdfInput').addEventListener('change',e=>{const files=[...(e.target.files||[])].filter(f=>f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf'));if(files.length){pendingPdfFiles.push(...files);renderPdfManager()}e.target.value=''});$('#deleteReportBtn').onclick=async()=>{const id=$('#reportId').value;if(id&&confirm(t('confirmDelete'))){await delReport(id);await delAllPdfs(id);$('#reportDialog').close();await renderAll()}};$('#newReportBtn').onclick=()=>openReport();$('#addMeasurementBtn').onclick=()=>addMeasurementRow();$('#closeDialogBtn').onclick=()=>$('#reportDialog').close();$('#catalogSearch').addEventListener('input',renderCatalog);$('#languageSelect').onchange=e=>{lang=e.target.value;applyLanguage()};$$('.segment').forEach(btn=>btn.onclick=()=>{$$('.segment').forEach(x=>x.classList.toggle('active',x===btn));$$('.view').forEach(v=>v.classList.remove('active'));$(`#${btn.dataset.view}View`).classList.add('active')});
function showUnlocked(){$('#lockScreen').classList.add('hidden');$('#appShell').setAttribute('aria-hidden','false');$('#pinInput').value='';$('#pinConfirmInput').value='';$('#lockError').textContent='';renderAll();renderCatalog()}function lockArchive(){vaultKey=null;pendingPdfFiles=[];removedPdfIds=[];currentPdfAttachments=[];if($('#reportDialog').open)$('#reportDialog').close();$('#appShell').setAttribute('aria-hidden','true');$('#lockScreen').classList.remove('hidden');renderLockState();$('#pinInput').focus()}$('#lockBtn').onclick=lockArchive;
$('#unlockBtn').onclick=async()=>{const pin=$('#pinInput').value,meta=await getMeta('security');$('#lockError').textContent='';if(pin.length<6){$('#lockError').textContent=t('short');return}if(!meta){if(pin!==$('#pinConfirmInput').value){$('#lockError').textContent=t('mismatch');return}await setupArchive(pin);showUnlocked()}else if(await unlockArchive(pin))showUnlocked();else $('#lockError').textContent=t('wrong')};$('#pinInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#unlockBtn').click()});
async function encryptedBackup(password){const salt=crypto.getRandomValues(new Uint8Array(16)),key=await deriveKey(password,salt),reports=await getAllReports(),pdfs=[];for(const r of reports){for(const p of await getPdfAttachments(r.id))pdfs.push({reportId:r.id,attachmentId:p.attachmentId==='legacy'?null:p.attachmentId,name:p.name,data:bytesToB64(await p.blob.arrayBuffer())})}const payload={schema:'riferto-portable',version:2,exportedAt:new Date().toISOString(),reports,pdfs};return{schema:'riferto-encrypted-backup',version:1,kdf:{name:'PBKDF2-SHA256',iterations:ITERATIONS,salt:bytesToB64(salt)},cipher:{name:'AES-GCM',...(await encryptJson(key,payload,'riferto-backup-v1'))}}}
$('#exportBtn').onclick=async()=>{const password=prompt(t('backupPrompt'));if(!password||password.length<6)return;const backup=await encryptedBackup(password),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}));a.download=`riferto-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('#importInput').onchange=async e=>{try{const outer=JSON.parse(await e.target.files[0].text());if(outer.schema!=='riferto-encrypted-backup'||outer.version!==1)throw new Error();const password=prompt(t('backupImport'));if(!password)throw new Error();const key=await deriveKey(password,b64ToBytes(outer.kdf.salt),outer.kdf.iterations||ITERATIONS),data=await decryptJson(key,outer.cipher,'riferto-backup-v1');if(data.schema!=='riferto-portable'||!Array.isArray(data.reports))throw new Error();for(const r of data.reports)await putReport(r);for(const p of data.pdfs||[])await putPdfAttachment(p.reportId,new Blob([b64ToBytes(p.data)],{type:'application/pdf'}),p.name,p.attachmentId||uuid());alert(t('importDone'));await renderAll()}catch{alert(t('badBackup'))}e.target.value=''};
async function init(){loinc=await fetch('./loinc-common.json',{cache:'no-store'}).then(r=>r.json());fillDatalist();applyLanguage();if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{})}init();