const DB_NAME='riferto-db',DB_VERSION=1,META_STORE='meta',ITERATIONS=310000;
const te=new TextEncoder(),td=new TextDecoder(),$=s=>document.querySelector(s);
const b64=bytes=>{const a=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);let x='';for(let i=0;i<a.length;i+=0x8000)x+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(x)};
const unb64=s=>{const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a};
const b64url=bytes=>b64(bytes).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb64url=s=>unb64(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4));
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('vault'))db.createObjectStore('vault',{keyPath:'id'});if(!db.objectStoreNames.contains(META_STORE))db.createObjectStore(META_STORE,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function req(mode,fn){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(META_STORE,mode),r=fn(tx.objectStore(META_STORE));r.onsuccess=()=>{db.close();resolve(r.result)};r.onerror=()=>{db.close();reject(r.error)}})}
const getMeta=id=>req('readonly',s=>s.get(id)),putMeta=x=>req('readwrite',s=>s.put(x)),delMeta=id=>req('readwrite',s=>s.delete(id));
async function deriveKey(secret,salt,iterations=ITERATIONS){const material=await crypto.subtle.importKey('raw',te.encode(secret),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function verifyPin(pin){const meta=await getMeta('security');if(!meta)return false;try{const key=await deriveKey(pin,unb64(meta.salt),meta.iterations||ITERATIONS);await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(meta.wrappedKey.iv),additionalData:te.encode('riferto-key-v1')},key,unb64(meta.wrappedKey.ciphertext));return true}catch{return false}}
async function aesFromPrf(prf){return crypto.subtle.importKey('raw',new Uint8Array(prf).slice(0,32),'AES-GCM',false,['encrypt','decrypt'])}
async function sealPin(key,pin){const iv=crypto.getRandomValues(new Uint8Array(12)),ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:te.encode('riferto-biometric-pin-v1')},key,te.encode(pin));return{iv:b64(iv),ciphertext:b64(ciphertext)}}
async function openPin(key,box){return td.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(box.iv),additionalData:te.encode('riferto-biometric-pin-v1')},key,unb64(box.ciphertext)))}
async function supported(){if(!window.isSecureContext||!window.PublicKeyCredential||!navigator.credentials)return false;try{return await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable()}catch{return false}}
function prfFirst(cred){return cred?.getClientExtensionResults?.()?.prf?.results?.first||null}
function derToRaw(sig,size=32){const b=new Uint8Array(sig);if(b[0]!==0x30)return b;let p=2;if(b[1]&0x80)p=2+(b[1]&0x7f);if(b[p++]!==0x02)throw new Error('Firma ECDSA non valida');let rl=b[p++];if(rl&0x80){const n=rl&0x7f;rl=0;for(let i=0;i<n;i++)rl=(rl<<8)|b[p++]}let r=b.slice(p,p+rl);p+=rl;if(b[p++]!==0x02)throw new Error('Firma ECDSA non valida');let sl=b[p++];if(sl&0x80){const n=sl&0x7f;sl=0;for(let i=0;i<n;i++)sl=(sl<<8)|b[p++]}let s=b.slice(p,p+sl);while(r.length>size&&r[0]===0)r=r.slice(1);while(s.length>size&&s[0]===0)s=s.slice(1);const out=new Uint8Array(size*2);const rr=r.slice(-size),ss=s.slice(-size);out.set(rr,size-rr.length);out.set(ss,size*2-ss.length);return out}
async function rpIdHashOk(authData){const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',te.encode(location.hostname))),a=new Uint8Array(authData).slice(0,32);return a.length===hash.length&&a.every((v,i)=>v===hash[i])}
async function verifyAssertion(credential,challenge,meta){const response=credential.response,client=JSON.parse(td.decode(response.clientDataJSON));if(client.type!=='webauthn.get'||client.origin!==location.origin)return false;const got=unb64url(client.challenge),want=new Uint8Array(challenge);if(got.length!==want.length||!got.every((v,i)=>v===want[i]))return false;const auth=new Uint8Array(response.authenticatorData);if(auth.length<37||!(await rpIdHashOk(auth)))return false;const flags=auth[32];if((flags&1)===0||(flags&4)===0)return false;const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',response.clientDataJSON)),signed=new Uint8Array(auth.length+hash.length);signed.set(auth);signed.set(hash,auth.length);let key,algorithm,signature=response.signature;if(meta.alg===-7){key=await crypto.subtle.importKey('spki',unb64(meta.publicKey),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);algorithm={name:'ECDSA',hash:'SHA-256'};signature=derToRaw(signature)}else if(meta.alg===-257){key=await crypto.subtle.importKey('spki',unb64(meta.publicKey),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);algorithm={name:'RSASSA-PKCS1-v1_5'}}else return false;return crypto.subtle.verify(algorithm,key,signature,signed)}
async function assertion(meta){const challenge=crypto.getRandomValues(new Uint8Array(32)),credId=unb64url(meta.credentialId);const cred=await navigator.credentials.get({publicKey:{challenge,rpId:location.hostname,allowCredentials:[{id:credId,type:'public-key'}],userVerification:'required',timeout:60000,extensions:{prf:{evalByCredential:{[meta.credentialId]:{first:unb64(meta.prfSalt)}}}}}});if(!(await verifyAssertion(cred,challenge,meta)))throw new Error('Verifica biometrica non valida');const prf=prfFirst(cred);if(!prf)throw new Error('PRF non disponibile su questo dispositivo/browser');return prf}
async function enroll(){if(!(await supported())){alert('Autenticazione biometrica WebAuthn non disponibile su questo dispositivo/browser.');return}const pin=prompt('Inserisci il PIN attuale di Riferto per abilitare Face ID / impronta.');if(!pin)return;if(!(await verifyPin(pin))){alert('PIN errato.');return}const prfSalt=crypto.getRandomValues(new Uint8Array(32)),challenge=crypto.getRandomValues(new Uint8Array(32)),userId=crypto.getRandomValues(new Uint8Array(32));const cred=await navigator.credentials.create({publicKey:{challenge,rp:{name:'Riferto',id:location.hostname},user:{id:userId,name:'riferto-local',displayName:'Riferto'},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],authenticatorSelection:{authenticatorAttachment:'platform',residentKey:'preferred',userVerification:'required'},attestation:'none',timeout:60000,extensions:{prf:{eval:{first:prfSalt}}}}});if(!cred)throw new Error('Creazione credenziale annullata');const response=cred.response,publicKey=response.getPublicKey?.(),alg=response.getPublicKeyAlgorithm?.();if(!publicKey||![-7,-257].includes(alg))throw new Error('Chiave WebAuthn non esportabile');const credentialId=b64url(cred.rawId);let prf=prfFirst(cred);if(!prf){prf=await assertion({credentialId,prfSalt:b64(prfSalt),publicKey:b64(publicKey),alg})}if(!prf)throw new Error('PRF non disponibile.');const key=await aesFromPrf(prf),pinBox=await sealPin(key,pin);await putMeta({id:'biometric',version:1,credentialId,prfSalt:b64(prfSalt),publicKey:b64(publicKey),alg,pinBox,origin:location.origin,rpId:location.hostname,createdAt:new Date().toISOString()});alert('Sblocco biometrico abilitato.');await refresh()}
async function unlockBiometric(){try{const meta=await getMeta('biometric');if(!meta)return;const prf=await assertion(meta),key=await aesFromPrf(prf),pin=await openPin(key,meta.pinBox);$('#pinInput').value=pin;$('#unlockBtn').click();setTimeout(()=>{$('#pinInput').value=''},500)}catch(e){console.error(e);alert(e?.message||'Sblocco biometrico non riuscito.')}}
async function refresh(){const meta=await getMeta('biometric'),ok=await supported();$('#biometricUnlockBtn')?.classList.toggle('hidden',!(ok&&meta));if($('#biometricManageBtn'))$('#biometricManageBtn').textContent=meta?'Disabilita biometria':'Face ID / impronta'}
$('#biometricUnlockBtn')?.addEventListener('click',unlockBiometric);$('#biometricManageBtn')?.addEventListener('click',async()=>{const meta=await getMeta('biometric');if(meta){if(confirm('Disabilitare lo sblocco biometrico su questo dispositivo?')){await delMeta('biometric');await refresh()}}else{try{await enroll()}catch(e){console.error(e);alert(e?.message||'Impossibile abilitare la biometria.')}}});refresh();