const DB_NAME='riferto-db',DB_VERSION=1,META_STORE='meta',ITERATIONS=310000;
const te=new TextEncoder(),td=new TextDecoder(),$=s=>document.querySelector(s);
const b64=bytes=>{const a=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);let x='';for(let i=0;i<a.length;i+=0x8000)x+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(x)};
const unb64=s=>{const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a};
const b64url=bytes=>b64(bytes).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb64url=s=>unb64(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4));
const isApple=/iPhone|iPad|Macintosh/i.test(navigator.userAgent);
const faceLabel=isApple?'Face ID':'Biometria dispositivo';
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('vault'))db.createObjectStore('vault',{keyPath:'id'});if(!db.objectStoreNames.contains(META_STORE))db.createObjectStore(META_STORE,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function req(mode,fn){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(META_STORE,mode),r=fn(tx.objectStore(META_STORE));r.onsuccess=()=>{db.close();resolve(r.result)};r.onerror=()=>{db.close();reject(r.error)}})}
const getMeta=id=>req('readonly',s=>s.get(id)),putMeta=x=>req('readwrite',s=>s.put(x)),delMeta=id=>req('readwrite',s=>s.delete(id));
const metaId=kind=>kind==='faceid'?'webauthn-faceid':'webauthn-passkey';
async function getCredentialMeta(kind){const current=await getMeta(metaId(kind));if(current)return current;if(kind==='faceid')return getMeta('biometric');return null}
async function deriveKey(secret,salt,iterations=ITERATIONS){const material=await crypto.subtle.importKey('raw',te.encode(secret),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function verifyPin(pin){const meta=await getMeta('security');if(!meta)return false;try{const key=await deriveKey(pin,unb64(meta.salt),meta.iterations||ITERATIONS);await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(meta.wrappedKey.iv),additionalData:te.encode('riferto-key-v1')},key,unb64(meta.wrappedKey.ciphertext));return true}catch{return false}}
async function aesFromPrf(prf){return crypto.subtle.importKey('raw',new Uint8Array(prf).slice(0,32),'AES-GCM',false,['encrypt','decrypt'])}
async function sealPin(key,pin,kind){const iv=crypto.getRandomValues(new Uint8Array(12)),ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:te.encode(`riferto-credential-pin-v1:${kind}`)},key,te.encode(pin));return{iv:b64(iv),ciphertext:b64(ciphertext)}}
async function openPin(key,box,kind){try{return td.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(box.iv),additionalData:te.encode(`riferto-credential-pin-v1:${kind}`)},key,unb64(box.ciphertext)))}catch{return td.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(box.iv),additionalData:te.encode('riferto-biometric-pin-v1')},key,unb64(box.ciphertext)))}}
async function webAuthnAvailable(){return Boolean(window.isSecureContext&&window.PublicKeyCredential&&navigator.credentials)}
async function platformAvailable(){if(!(await webAuthnAvailable())||!PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable)return false;try{return await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable()}catch{return false}}
function prfFirst(cred){return cred?.getClientExtensionResults?.()?.prf?.results?.first||null}
function derToRaw(sig,size=32){const b=new Uint8Array(sig);if(b[0]!==0x30)return b;let p=2;if(b[1]&0x80)p=2+(b[1]&0x7f);if(b[p++]!==0x02)throw new Error('Firma ECDSA non valida');let rl=b[p++];if(rl&0x80){const n=rl&0x7f;rl=0;for(let i=0;i<n;i++)rl=(rl<<8)|b[p++]}let r=b.slice(p,p+rl);p+=rl;if(b[p++]!==0x02)throw new Error('Firma ECDSA non valida');let sl=b[p++];if(sl&0x80){const n=sl&0x7f;sl=0;for(let i=0;i<n;i++)sl=(sl<<8)|b[p++]}let s=b.slice(p,p+sl);while(r.length>size&&r[0]===0)r=r.slice(1);while(s.length>size&&s[0]===0)s=s.slice(1);const out=new Uint8Array(size*2);const rr=r.slice(-size),ss=s.slice(-size);out.set(rr,size-rr.length);out.set(ss,size*2-ss.length);return out}
async function rpIdHashOk(authData){const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',te.encode(location.hostname))),a=new Uint8Array(authData).slice(0,32);return a.length===hash.length&&a.every((v,i)=>v===hash[i])}
async function verifyAssertion(credential,challenge,meta){const response=credential.response,client=JSON.parse(td.decode(response.clientDataJSON));if(client.type!=='webauthn.get'||client.origin!==location.origin)return false;const got=unb64url(client.challenge),want=new Uint8Array(challenge);if(got.length!==want.length||!got.every((v,i)=>v===want[i]))return false;const auth=new Uint8Array(response.authenticatorData);if(auth.length<37||!(await rpIdHashOk(auth)))return false;const flags=auth[32];if((flags&1)===0||(flags&4)===0)return false;const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',response.clientDataJSON)),signed=new Uint8Array(auth.length+hash.length);signed.set(auth);signed.set(hash,auth.length);let key,algorithm,signature=response.signature;if(meta.alg===-7){key=await crypto.subtle.importKey('spki',unb64(meta.publicKey),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);algorithm={name:'ECDSA',hash:'SHA-256'};signature=derToRaw(signature)}else if(meta.alg===-257){key=await crypto.subtle.importKey('spki',unb64(meta.publicKey),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);algorithm={name:'RSASSA-PKCS1-v1_5'}}else return false;return crypto.subtle.verify(algorithm,key,signature,signed)}
function assertionRequest(meta){const challenge=crypto.getRandomValues(new Uint8Array(32)),credId=unb64url(meta.credentialId);const promise=navigator.credentials.get({publicKey:{challenge,rpId:location.hostname,allowCredentials:[{id:credId,type:'public-key'}],userVerification:'required',timeout:60000,extensions:{prf:{evalByCredential:{[meta.credentialId]:{first:unb64(meta.prfSalt)}}}}}});return{challenge,promise}}
async function finishAssertion(request,meta){const cred=await request.promise;if(!(await verifyAssertion(cred,request.challenge,meta)))throw new Error('Verifica WebAuthn non valida');const prf=prfFirst(cred);if(!prf)throw new Error('Questa credenziale non espone PRF: non può sbloccare Riferto senza PIN.');return prf}
function creationRequest(kind){const prfSalt=crypto.getRandomValues(new Uint8Array(32)),challenge=crypto.getRandomValues(new Uint8Array(32)),userId=crypto.getRandomValues(new Uint8Array(32));const selection={residentKey:kind==='passkey'?'required':'preferred',userVerification:'required'};if(kind==='faceid')selection.authenticatorAttachment='platform';const promise=navigator.credentials.create({publicKey:{challenge,rp:{name:'Riferto',id:location.hostname},user:{id:userId,name:`riferto-${kind}`,displayName:kind==='faceid'?faceLabel:'Riferto Passkey'},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],authenticatorSelection:selection,attestation:'none',timeout:60000,extensions:{prf:{eval:{first:prfSalt}}}}});return{prfSalt,promise}}
async function parseCreatedCredential(request,kind){const cred=await request.promise;if(!cred)throw new Error('Creazione credenziale annullata');const response=cred.response,publicKey=response.getPublicKey?.(),alg=response.getPublicKeyAlgorithm?.();if(!publicKey||![-7,-257].includes(alg))throw new Error('Chiave WebAuthn non esportabile');return{id:metaId(kind),kind,version:2,credentialId:b64url(cred.rawId),prfSalt:b64(request.prfSalt),publicKey:b64(publicKey),alg,origin:location.origin,rpId:location.hostname,createdAt:new Date().toISOString(),prf:prfFirst(cred)}}

const style=document.createElement('style');style.textContent=`.credential-dialog{border:0;background:transparent;padding:0;width:min(92vw,420px)}.credential-dialog::backdrop{background:rgba(15,25,40,.35);backdrop-filter:blur(10px)}.credential-panel{padding:22px;border-radius:28px}.credential-dots{display:flex;justify-content:center;gap:12px;margin:18px 0}.credential-dot{width:14px;height:14px;border-radius:50%;border:2px solid #49617f}.credential-dot.filled{background:#10203a}.credential-keypad{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.credential-key{border:0;border-radius:18px;min-height:54px;background:rgba(255,255,255,.72);font-size:1.3rem;font-weight:800}.credential-actions{display:grid;gap:10px;margin-top:16px}.credential-status{min-height:1.3em;color:#61708a;font-size:.82rem;text-align:center}`;document.head.appendChild(style);
const dialog=document.createElement('dialog');dialog.className='credential-dialog';dialog.innerHTML=`<section class="credential-panel glass"><p class="eyebrow">Sicurezza</p><h3 id="credentialTitle">Configura accesso</h3><p id="credentialText" class="muted">Conferma il PIN di Riferto.</p><div id="credentialDots" class="credential-dots"></div><div class="credential-keypad">${[1,2,3,4,5,6,7,8,9].map(n=>`<button type="button" class="credential-key" data-cred-key="${n}">${n}</button>`).join('')}<span></span><button type="button" class="credential-key" data-cred-key="0">0</button><button type="button" class="credential-key" data-cred-key="delete" aria-label="Cancella">⌫</button></div><p id="credentialStatus" class="credential-status"></p><div class="credential-actions"><button id="credentialAction" type="button" class="primary-btn">Verifica PIN</button><button id="credentialCancel" type="button" class="secondary-btn">Annulla</button></div></section>`;document.body.appendChild(dialog);
let setupKind='faceid',setupPin='',setupStage='pin',pendingMeta=null;
const title=$('#credentialTitle'),text=$('#credentialText'),dotsEl=$('#credentialDots'),statusEl=$('#credentialStatus'),actionBtn=$('#credentialAction');
function renderSetup(){dotsEl.innerHTML=Array.from({length:6},(_,i)=>`<span class="credential-dot${i<setupPin.length?' filled':''}"></span>`).join('');const label=setupKind==='faceid'?faceLabel:'Passkey';title.textContent=`Configura ${label}`;if(setupStage==='pin'){text.textContent='Inserisci il PIN attuale di Riferto.';actionBtn.textContent='Verifica PIN'}else if(setupStage==='create'){text.textContent=`PIN verificato. Tocca il pulsante per avviare ${label}.`;actionBtn.textContent=`Continua con ${label}`}else{text.textContent='La credenziale è stata creata. Completa ora la verifica per collegarla a Riferto.';actionBtn.textContent='Completa configurazione'}}
function openSetup(kind){setupKind=kind;setupPin='';setupStage='pin';pendingMeta=null;statusEl.textContent='';actionBtn.disabled=false;renderSetup();dialog.showModal()}
dialog.addEventListener('click',e=>{const b=e.target.closest('[data-cred-key]');if(!b||setupStage!=='pin')return;const k=b.dataset.credKey;if(k==='delete')setupPin=setupPin.slice(0,-1);else if(setupPin.length<6)setupPin+=k;statusEl.textContent='';renderSetup()});
$('#credentialCancel').onclick=()=>dialog.close();
actionBtn.onclick=async()=>{try{if(setupStage==='pin'){if(setupPin.length!==6){statusEl.textContent='Inserisci 6 cifre.';return}actionBtn.disabled=true;const ok=await verifyPin(setupPin);actionBtn.disabled=false;if(!ok){statusEl.textContent='PIN errato.';return}setupStage='create';statusEl.textContent='';renderSetup();return}if(setupStage==='create'){dialog.close();const request=creationRequest(setupKind);const meta=await parseCreatedCredential(request,setupKind);if(meta.prf){const key=await aesFromPrf(meta.prf);meta.pinBox=await sealPin(key,setupPin,setupKind);delete meta.prf;await putMeta(meta);setupPin='';await refresh();alert(`${setupKind==='faceid'?faceLabel:'Passkey'} configurata.`);return}pendingMeta=meta;setupStage='complete';statusEl.textContent='';renderSetup();dialog.showModal();return}if(setupStage==='complete'&&pendingMeta){dialog.close();const request=assertionRequest(pendingMeta);const prf=await finishAssertion(request,pendingMeta);const key=await aesFromPrf(prf);pendingMeta.pinBox=await sealPin(key,setupPin,setupKind);delete pendingMeta.prf;await putMeta(pendingMeta);setupPin='';pendingMeta=null;await refresh();alert(`${setupKind==='faceid'?faceLabel:'Passkey'} configurata.`)}}catch(e){console.error(e);statusEl.textContent=e?.message||'Configurazione non riuscita.';if(!dialog.open)dialog.showModal()}};

const faceManage=$('#biometricManageBtn');if(faceManage)faceManage.textContent=faceLabel;
const passManage=document.createElement('button');passManage.id='passkeyManageBtn';passManage.className='secondary-btn';passManage.type='button';passManage.textContent='Passkey';faceManage?.after(passManage);
const faceUnlock=$('#biometricUnlockBtn');if(faceUnlock)faceUnlock.textContent=`Sblocca con ${faceLabel}`;
const passUnlock=document.createElement('button');passUnlock.id='passkeyUnlockBtn';passUnlock.className='secondary-btn hidden';passUnlock.type='button';passUnlock.textContent='Sblocca con Passkey';faceUnlock?.after(passUnlock);
async function unlockKind(kind){try{const meta=await getCredentialMeta(kind);if(!meta)return;const request=assertionRequest(meta),prf=await finishAssertion(request,meta),key=await aesFromPrf(prf),pin=await openPin(key,meta.pinBox,meta.kind||kind);$('#pinInput').value=pin;$('#unlockBtn').click();setTimeout(()=>{$('#pinInput').value=''},500)}catch(e){console.error(e);alert(e?.message||'Sblocco non riuscito.')}}
async function toggleKind(kind){const meta=await getCredentialMeta(kind),label=kind==='faceid'?faceLabel:'Passkey';if(meta){if(confirm(`Disabilitare ${label}?`)){await delMeta(meta.id||metaId(kind));if(kind==='faceid')await delMeta('biometric').catch(()=>{});await refresh()}}else openSetup(kind)}
async function refresh(){const [face,pass,platform,web]=await Promise.all([getCredentialMeta('faceid'),getCredentialMeta('passkey'),platformAvailable(),webAuthnAvailable()]);if(faceUnlock)faceUnlock.classList.toggle('hidden',!(platform&&face));passUnlock.classList.toggle('hidden',!(web&&pass));if(faceManage){faceManage.disabled=!platform&&!face;faceManage.textContent=face?`Disabilita ${faceLabel}`:faceLabel}passManage.disabled=!web&&!pass;passManage.textContent=pass?'Disabilita Passkey':'Passkey'}
faceUnlock?.addEventListener('click',()=>unlockKind('faceid'));passUnlock.addEventListener('click',()=>unlockKind('passkey'));faceManage?.addEventListener('click',()=>toggleKind('faceid'));passManage.addEventListener('click',()=>toggleKind('passkey'));refresh();