const section=document.querySelector('.app-section[data-section="trend"]');
const reportsList=document.querySelector('#reportsList');
if(!section)throw new Error('Trend section missing');

const FAVORITES_KEY='riferto-trend-favorites';
let favorites=new Set(JSON.parse(localStorage.getItem(FAVORITES_KEY)||'[]'));
let viewMode='matrix';

const style=document.createElement('style');
style.textContent=`
.trend-hero{padding:18px;margin-bottom:14px}.trend-hero h2{margin:4px 0 7px}.trend-panel{padding:14px;margin-bottom:14px;display:grid;gap:12px}.trend-filter-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(150px,.55fr);gap:10px}.trend-date-custom{display:grid;grid-template-columns:1fr 1fr;gap:8px}.trend-date-custom.hidden{display:none}.trend-segment{display:grid;grid-template-columns:repeat(3,1fr);gap:3px;padding:3px;border-radius:14px;background:rgba(92,116,150,.1)}.trend-segment button{border:0;background:transparent;border-radius:11px;padding:8px 7px;font-weight:750;color:var(--muted);font-size:.72rem}.trend-segment button.active{background:rgba(255,255,255,.9);color:var(--text);box-shadow:0 1px 5px rgba(50,70,100,.08)}.trend-exam-picker{display:grid;gap:7px;max-height:210px;overflow:auto;padding:3px}.trend-exam-row{display:grid;grid-template-columns:34px minmax(0,1fr);align-items:center;gap:8px;padding:7px 8px;border-radius:12px;background:rgba(255,255,255,.42)}.trend-star{border:0;background:transparent;font-size:1.2rem;color:#8a98ac;padding:4px}.trend-star.active{color:#e2a300}.trend-exam-copy{min-width:0}.trend-exam-copy strong{display:block;font-size:.78rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.trend-exam-copy small{display:block;color:var(--muted);font-size:.65rem}.trend-result{padding:15px;display:grid;gap:14px}.trend-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.trend-head h3{margin:0}.trend-unit{font-size:.72rem;color:var(--muted)}.trend-chart-wrap{width:100%;overflow:hidden}.trend-chart{display:block;width:100%;height:auto;min-height:220px}.trend-axis{stroke:rgba(70,94,126,.18);stroke-width:1}.trend-line{fill:none;stroke:currentColor;stroke-width:2.5;stroke-linecap:round;stroke-linejoin:round}.trend-point{fill:currentColor}.trend-label{font-size:10px;fill:var(--muted)}.trend-value-label{font-size:10px;fill:var(--text);font-weight:700}.trend-table-wrap{overflow:auto;max-width:100%}.trend-table{width:100%;border-collapse:collapse;font-size:.75rem;white-space:nowrap}.trend-table th,.trend-table td{padding:8px 7px;border-bottom:1px solid rgba(80,105,140,.09);text-align:left}.trend-table th{position:sticky;top:0;background:rgba(245,249,255,.96);z-index:2}.trend-matrix th:first-child,.trend-matrix td:first-child{position:sticky;left:0;background:rgba(245,249,255,.97);z-index:3;max-width:170px;white-space:normal}.trend-matrix th:first-child{z-index:4}.trend-matrix td:not(:first-child){text-align:center}.trend-outlier{color:#b12424;font-weight:850}.trend-empty{text-align:center;padding:28px 18px}.trend-note{font-size:.68rem;color:var(--muted)}@media(max-width:520px){.trend-filter-grid{grid-template-columns:1fr}.trend-panel,.trend-result{padding:12px}.trend-segment button{font-size:.66rem;padding:8px 4px}.trend-matrix th:first-child,.trend-matrix td:first-child{max-width:125px}}
`;
document.head.appendChild(style);

section.innerHTML=`
<section class="glass trend-hero"><p class="eyebrow">Trend</p><h2>I tuoi esami nel tempo</h2><p class="muted">Confronta tutti i valori, filtra gli esami e salva i preferiti.</p></section>
<section class="glass trend-panel">
 <div class="trend-filter-grid"><label class="field"><span>Filtra esami</span><input id="trendSearch" type="search" placeholder="Es. emoglobina, creatinina…"></label><label class="field"><span>Periodo</span><select id="trendPeriod" class="glass-control"><option value="quarter">Ultimo trimestre</option><option value="year" selected>Quest’anno</option><option value="12m">Ultimi 12 mesi</option><option value="all">Tutto</option><option value="custom">Personalizzato</option></select></label></div>
 <div id="trendCustomDates" class="trend-date-custom hidden"><label class="field"><span>Da</span><input id="trendFrom" type="date"></label><label class="field"><span>A</span><input id="trendTo" type="date"></label></div>
 <label style="display:flex;align-items:center;gap:8px;font-size:.75rem"><input id="trendFavoritesOnly" type="checkbox"> Solo preferiti</label>
 <div id="trendExamPicker" class="trend-exam-picker"></div>
 <label class="field"><span>Esame per grafico</span><select id="trendGraphExam" class="glass-control"></select></label>
 <div class="trend-segment" aria-label="Vista"><button type="button" data-view="chart">Grafico</button><button type="button" data-view="detail">Dettaglio</button><button type="button" data-view="matrix" class="active">Matrice</button></div>
</section>
<section id="trendOutput" class="glass trend-result"></section>`;

const searchInput=section.querySelector('#trendSearch'),periodSelect=section.querySelector('#trendPeriod'),customDates=section.querySelector('#trendCustomDates'),fromInput=section.querySelector('#trendFrom'),toInput=section.querySelector('#trendTo'),favoritesOnly=section.querySelector('#trendFavoritesOnly'),picker=section.querySelector('#trendExamPicker'),graphExam=section.querySelector('#trendGraphExam'),output=section.querySelector('#trendOutput');

const months={gennaio:1,febbraio:2,marzo:3,aprile:4,maggio:5,giugno:6,luglio:7,agosto:8,settembre:9,ottobre:10,novembre:11,dicembre:12,january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12};
function parseDateLabel(label){const p=String(label||'').trim().toLowerCase().replace(/,/g,'').split(/\s+/);if(p.length<3)return null;const day=Number(p[0]),month=months[p[1]],year=Number(p[2]);if(!day||!month||!year)return null;const iso=`${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`;return{day,month,year,iso,date:new Date(`${iso}T12:00:00`)}}
function numeric(v){const m=String(v||'').match(/[-+]?\d+(?:[.,]\d+)?/);if(!m)return null;const n=Number(m[0].replace(',','.'));return Number.isFinite(n)?n:null}
function parseRange(text){const m=String(text||'').match(/([\d.,]+)\s*[–—-]\s*([\d.,]+)/);return m?[Number(m[1].replace(',','.')),Number(m[2].replace(',','.'))]:[null,null]}
function observations(){const out=[];for(const card of [...(reportsList?.querySelectorAll('.report-card')||[])]){const date=parseDateLabel(card.querySelector('.report-top h3')?.textContent);if(!date)continue;const lab=card.querySelector('.report-meta')?.textContent?.trim()||'';for(const item of [...card.querySelectorAll('.measurement-item')]){const name=item.querySelector('.measurement-name')?.textContent?.trim()||'',codeText=item.querySelector('.measurement-code')?.textContent||'',code=codeText.match(/LOINC\s+([^·\s]+)/i)?.[1]||name,raw=item.querySelector('.measurement-value')?.textContent?.trim()||'',value=numeric(raw);if(value===null)continue;const num=raw.match(/[-+]?\d+(?:[.,]\d+)?/),unit=num?raw.slice((num.index||0)+num[0].length).trim():'';const [min,max]=parseRange(codeText);out.push({key:code,name,code,value,unit,min,max,date,lab})}}return out}
function periodBounds(){const now=new Date(),mode=periodSelect.value;if(mode==='all')return[null,null];if(mode==='custom')return[fromInput.value?new Date(`${fromInput.value}T00:00:00`):null,toInput.value?new Date(`${toInput.value}T23:59:59`):null];let from;if(mode==='year')from=new Date(now.getFullYear(),0,1);else if(mode==='quarter'){from=new Date(now);from.setMonth(from.getMonth()-3)}else{from=new Date(now);from.setMonth(from.getMonth()-12)}return[from,now]}
function filteredObs(){const [from,to]=periodBounds();return observations().filter(o=>(!from||o.date.date>=from)&&(!to||o.date.date<=to))}
function examMap(rows=filteredObs()){const m=new Map();for(const o of rows)if(!m.has(o.key))m.set(o.key,{key:o.key,name:o.name,code:o.code});return m}
function visibleExamKeys(){const q=searchInput.value.trim().toLowerCase(),m=examMap();return [...m.values()].filter(e=>(!q||e.name.toLowerCase().includes(q)||e.code.toLowerCase().includes(q))&&(!favoritesOnly.checked||favorites.has(e.key))).sort((a,b)=>a.name.localeCompare(b.name,'it')).map(e=>e.key)}
function fmt(v){return Number.isInteger(v)?String(v):v.toLocaleString('it-IT',{maximumFractionDigits:2})}
function isOut(o){return o.min!==null&&o.max!==null&&(o.value<o.min||o.value>o.max)}
function saveFavorites(){localStorage.setItem(FAVORITES_KEY,JSON.stringify([...favorites]))}
function rebuildPicker(){const m=examMap(),keys=visibleExamKeys();picker.innerHTML=keys.length?keys.map(k=>{const e=m.get(k);return`<div class="trend-exam-row"><button type="button" class="trend-star ${favorites.has(k)?'active':''}" data-fav="${k}" aria-label="Preferito">★</button><div class="trend-exam-copy"><strong>${e.name}</strong><small>LOINC ${e.code}</small></div></div>`}).join(''):'<div class="trend-note">Nessun esame con questi filtri.</div>';const current=graphExam.value;graphExam.innerHTML=keys.map(k=>{const e=m.get(k);return`<option value="${k}">${e.name}</option>`}).join('');if(keys.includes(current))graphExam.value=current;render()}
function chartSvg(rows){if(!rows.length)return'';const w=640,h=250,p={l:42,r:18,t:28,b:42};let min=Math.min(...rows.map(d=>d.value)),max=Math.max(...rows.map(d=>d.value));if(min===max){min-=1;max+=1}const x=i=>p.l+i*(w-p.l-p.r)/Math.max(1,rows.length-1),y=v=>p.t+(max-v)*(h-p.t-p.b)/(max-min),path=rows.map((d,i)=>`${i?'L':'M'} ${x(i).toFixed(1)} ${y(d.value).toFixed(1)}`).join(' ');return`<svg class="trend-chart" viewBox="0 0 ${w} ${h}">${[0,.25,.5,.75,1].map(t=>{const yy=p.t+t*(h-p.t-p.b),val=max-t*(max-min);return`<line class="trend-axis" x1="${p.l}" x2="${w-p.r}" y1="${yy}" y2="${yy}"/><text class="trend-label" x="4" y="${yy+3}">${fmt(val)}</text>`}).join('')}<path class="trend-line" d="${path}"/>${rows.map((d,i)=>`<circle class="trend-point" cx="${x(i)}" cy="${y(d.value)}" r="4"/><text class="trend-value-label" text-anchor="middle" x="${x(i)}" y="${Math.max(12,y(d.value)-9)}">${fmt(d.value)}</text><text class="trend-label" text-anchor="middle" x="${x(i)}" y="${h-14}">${d.date.iso.slice(5)}</text>`).join('')}</svg>`}
function renderChart(rows,keys){const key=graphExam.value||keys[0];if(!key){output.innerHTML='<div class="trend-empty">Nessun dato disponibile.</div>';return}const all=rows.filter(o=>o.key===key).sort((a,b)=>a.date.iso.localeCompare(b.date.iso)),latest=all.at(-1);if(!latest){output.innerHTML='<div class="trend-empty">Nessun dato disponibile.</div>';return}const same=all.filter(o=>o.unit===latest.unit);output.innerHTML=`<div class="trend-head"><div><h3>${latest.name}</h3><div class="trend-unit">LOINC ${latest.code} · ${latest.unit||'unità non indicata'}</div></div><span class="pill">${same.length} valori</span></div><div class="trend-chart-wrap">${chartSvg(same)}</div>${same.length!==all.length?`<div class="trend-note">${all.length-same.length} valore/i con unità diversa esclusi dal grafico.</div>`:''}`}
function renderDetail(rows,keys){const keep=new Set(keys),data=rows.filter(o=>keep.has(o.key)).sort((a,b)=>b.date.iso.localeCompare(a.date.iso)||a.name.localeCompare(b.name));output.innerHTML=data.length?`<div class="trend-table-wrap"><table class="trend-table"><thead><tr><th>Data</th><th>Esame</th><th>Valore</th><th>Range</th><th>Struttura</th></tr></thead><tbody>${data.map(o=>`<tr><td>${o.date.iso.split('-').reverse().join('/')}</td><td>${o.name}</td><td class="${isOut(o)?'trend-outlier':''}">${fmt(o.value)} ${o.unit}${isOut(o)?' *':''}</td><td>${o.min!==null&&o.max!==null?`${fmt(o.min)}–${fmt(o.max)}`:'—'}</td><td>${o.lab||'—'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="trend-empty">Nessun dato disponibile.</div>'}
function renderMatrix(rows,keys){const keep=new Set(keys),data=rows.filter(o=>keep.has(o.key)),dates=[...new Set(data.map(o=>o.date.iso))].sort(),m=examMap(data);if(!dates.length){output.innerHTML='<div class="trend-empty">Nessun dato disponibile.</div>';return}const by=new Map(data.map(o=>[`${o.key}|${o.date.iso}`,o]));output.innerHTML=`<div class="trend-table-wrap"><table class="trend-table trend-matrix"><thead><tr><th>Esame</th>${dates.map(d=>`<th>${d.slice(8)}/${d.slice(5,7)}</th>`).join('')}</tr></thead><tbody>${keys.filter(k=>m.has(k)).map(k=>{const e=m.get(k);return`<tr><td><strong>${e.name}</strong><br><small>LOINC ${e.code}</small></td>${dates.map(d=>{const o=by.get(`${k}|${d}`);return`<td class="${o&&isOut(o)?'trend-outlier':''}">${o?`${fmt(o.value)} ${o.unit}${isOut(o)?' *':''}`:'—'}</td>`}).join('')}</tr>`}).join('')}</tbody></table></div>`}
function render(){const rows=filteredObs(),keys=visibleExamKeys();if(viewMode==='chart')renderChart(rows,keys);else if(viewMode==='detail')renderDetail(rows,keys);else renderMatrix(rows,keys)}

picker.addEventListener('click',e=>{const b=e.target.closest('[data-fav]');if(!b)return;const k=b.dataset.fav;favorites.has(k)?favorites.delete(k):favorites.add(k);saveFavorites();rebuildPicker()});
searchInput.addEventListener('input',rebuildPicker);favoritesOnly.addEventListener('change',rebuildPicker);graphExam.addEventListener('change',render);periodSelect.addEventListener('change',()=>{customDates.classList.toggle('hidden',periodSelect.value!=='custom');rebuildPicker()});fromInput.addEventListener('change',rebuildPicker);toInput.addEventListener('change',rebuildPicker);
section.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>{viewMode=btn.dataset.view;section.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===btn));render()}));
if(reportsList)new MutationObserver(()=>requestAnimationFrame(rebuildPicker)).observe(reportsList,{childList:true,subtree:true});
rebuildPicker();
